### PR TITLE
Fix the `isdigit` error.

### LINKED ISSUE #14: AttributeError: 'int' object has no attribute 'isdigit'
I've got this error while trying to run example from README:

```
$ dockerize -t sed /bin/sed
Traceback (most recent call last):
  File "/home/kvs/.local/bin/dockerize", line 11, in <module>
    sys.exit(main())
  File "/home/kvs/.local/lib/python3.5/site-packages/dockerize/main.py", line 125, in main
    app.build()
  File "/home/kvs/.local/lib/python3.5/site-packages/dockerize/dockerize.py", line 122, in build
    self.resolve_deps()
  File "/home/kvs/.local/lib/python3.5/site-packages/dockerize/dockerize.py", line 200, in resolve_deps
    deps.add(path)
  File "/home/kvs/.local/lib/python3.5/site-packages/dockerize/depsolver.py", line 110, in add
    self.get_deps(path)
  File "/home/kvs/.local/lib/python3.5/site-packages/dockerize/depsolver.py", line 81, in get_deps
    elf = ELFFile(path)
  File "/home/kvs/.local/lib/python3.5/site-packages/dockerize/depsolver.py", line 36, in __init__
    self.read_sections()
  File "/home/kvs/.local/lib/python3.5/site-packages/dockerize/depsolver.py", line 48, in read_sections
    if not line or not line[0].isdigit():
AttributeError: 'int' object has no attribute 'isdigit'
```
Used version (installed via pip):

```
$ dockerize --version
dockerize version 0.2.2
```

### PR DESCRIPTION
**Pull request by iddm**
Fixes #14

### CODE REVIEW

**Comment by homonymous** [comment]
@larsks Please merge it, this error is blocking me.

**Comment by iddm** [comment]
@homonymous I doubt @larsks will ever merge this, just use my fork now.

**Comment by larsks** [comment]
Oh, larsks just might :)

**Comment by vityafx** [comment]
What stopped you from reviewing and/or merging/closing this pull request a year ago? :)

**Comment by larsks** [comment]
I've merged a modified version of this PR. Cheers!

**Pull request merged**
